#-----------------------------------------------------------------------------------
# Configuration for generating new surnames.
#-----------------------------------------------------------------------------------
# - data_path               : The csv path to the training data.
# - model_path              : The path to the saved model.
# - model_name              : The name of the model.
# - num_samples             : Number of surnames to generate.
# - embedding_dim           : Dimension of character embeddings.
# - hidden_size             : Hidden size of `rnn`, `gru` or `lstm` model.
# - dropout                 : Dropout value to apply after the `rnn`, `gru or `lstm`
#                             layer.
# - num_layers              : Number of `rnn`, `gru` or `lstm` layers.
# - with_condition          : If ``True`` the surname nationalities will be also
#                             passed as an input in the `rnn`, `gru` or `lstm` layer(s).
#-----------------------------------------------------------------------------------
data_path: ./data/surnames/processed/train.csv
model_path: ./checkpoints/lstmgenerator_conditioned.pth
model_name: lstm_generator
num_samples: 10
model_init_params:
  embedding_dim: 100
  hidden_size: 100
  dropout: 0.1
  num_layers: 1
  with_condition: True
